name: Snap Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:

  build-and-test-arm64:
    runs-on: Ubuntu_ARM64_4C_16G_01
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
   
      - name: Build Snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.*'
          cache: false

      - name: Run tests
        working-directory: tests
        env:
          MOCK_GPIO: true
          TEARDOWN: false
          SNAP_PATH: ../${{ steps.snapcraft.outputs.snap }}
        run: go test -failfast -p 1 -timeout 20m -v

      - name: Upload snap logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snap-logs
          path: tests/*.log

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: matter-pi-gpio-commander_${{ github.run_number}}_arm64.snap
          path: ${{ steps.snapcraft.outputs.snap }}
  